import { mediaRecordSchema, validateUnique, type MediaRecord } from "@/lib/schemas";

const records: MediaRecord[] = [
  { id: "tag-hero", filename: "tag-twin-integrated-runtime.webp", aspectRatio: "16:9", minimumDimensions: "1920×1080", caption: "Integrated UE5 research demonstrator showing flood, evacuation, agents, and priority-event interaction.", alt: "Unreal Engine view of Minxiong terrain with flood water, evacuation routes, moving agents, and a ranked event panel.", ownership: "lab-permission-required", redactions: "Remove project paths, addresses, credentials, usernames, debug overlays, and sensitive route labels.", status: "required" },
  { id: "flood-progression", filename: "tag-twin-flood-progression.webp", aspectRatio: "2:1", minimumDimensions: "2400×1200", caption: "Four matched views showing dry terrain, flood onset, wider inundation, and recession.", alt: "Four locked-camera Unreal Engine views showing flood progression.", ownership: "lab-permission-required", redactions: "Use one camera; remove editor chrome and private labels.", status: "required" },
  { id: "qgis-mesh", filename: "tag-twin-qgis-adaptive-mesh.webp", aspectRatio: "16:9", minimumDimensions: "1600×900", caption: "Adaptive HEC-RAS polygon mesh inspected in QGIS before conversion.", alt: "QGIS view of irregular flood-simulation polygons and hydraulic attributes.", ownership: "lab-permission-required", redactions: "Hide identifiers, paths, drive references, and any non-public basemap labels.", status: "required" },
  { id: "input-output", filename: "tag-twin-input-output-comparison.webp", aspectRatio: "16:9", minimumDimensions: "1920×1080", caption: "The same flood state across source mesh, reference raster, and UE5 visualization.", alt: "Three-panel comparison of HEC-RAS polygons, reference raster, and Unreal flood geometry.", ownership: "lab-permission-required", redactions: "Confirm dataset license and match extent and orientation.", status: "required" },
  { id: "frame-04", filename: "tag-twin-frame-04-consistency.webp", aspectRatio: "16:9", minimumDimensions: "1600×900", caption: "Frame 04 visualization-consistency comparison between the reference and 512-grid masks.", alt: "Flood mask confusion map showing true wet, false wet, false dry, and dry regions.", ownership: "lab-permission-required", redactions: "Label as visualization consistency, not field accuracy.", status: "required" },
  { id: "resolution", filename: "tag-twin-256-512-boundary.webp", aspectRatio: "2:1", minimumDimensions: "1800×900", caption: "Matched shoreline close-ups comparing 256 and 512 playback grids.", alt: "Two shoreline close-ups showing blockier 256-grid and smoother 512-grid flood geometry.", ownership: "lab-permission-required", redactions: "Use matched location, camera, and lighting.", status: "required" },
  { id: "lab-portrait", filename: "akash-lab-workstation.webp", aspectRatio: "3:2", minimumDimensions: "1800×1200", caption: "Developing and validating the visualization pipeline in the graduate research lab.", alt: "Akash working at a lab workstation with Unreal Engine and QGIS visible.", ownership: "owned", redactions: "Blur messages, IDs, filenames, private addresses, badges, and non-consenting people.", status: "required" },
  { id: "lab-demo", filename: "tag-twin-lab-demonstration.webp", aspectRatio: "16:9", minimumDimensions: "1920×1080", caption: "A lab demonstration of the integrated research prototype.", alt: "Akash presenting the Disaster Response Digital Twin Model demonstrator to lab collaborators.", ownership: "third-party-permission-required", redactions: "Obtain consent from every identifiable person; hide private notes and chat.", status: "optional" },
];

export const mediaManifest = validateUnique(records.map((record) => mediaRecordSchema.parse(record)), "media record");
