import { resumeEntrySchema, validateUnique, type ResumeEntry } from "@/lib/schemas";

export const resumeSectionOrder = ["education", "experience", "award", "project"] as const;

const records = [
  {
    id: "masters-advanced-manufacturing",
    section: "education",
    status: "Current",
    dates: "Aug 2025 — present",
    sortDate: "2025-08",
    title: "M.S. Advanced Manufacturing",
    organization: "AIM-HI · National Chung Cheng University",
    location: "Chiayi, Taiwan",
    summary: "Graduate study connecting artificial intelligence, precision engineering, digital twins, and industrial automation.",
    preview: [
      "Current graduate coursework and research focus on advanced manufacturing systems, scientific visualization, geospatial integration, and data-driven engineering.",
      "The program is supported through the International Industrial Talents Education Special Program fellowship."
    ],
    skills: ["Advanced manufacturing", "Digital twins", "Scientific computing", "Research methods"],
    metric: "89%",
    visual: { kind: "logo", key: "ccu" },
  },
  {
    id: "bachelors-computer-science",
    section: "education",
    status: "Completed",
    dates: "Aug 2021 — Aug 2025",
    sortDate: "2021-08",
    title: "B.Tech. Computer Science",
    organization: "Amity University Mumbai",
    location: "Mumbai, India",
    summary: "Computer-science training centered on artificial intelligence, machine learning, software systems, and applied problem solving.",
    preview: [
      "Coursework and project work covered neural networks, data structures, algorithms, computer vision, application development, statistics, and digital systems.",
      "The degree concluded with an undergraduate thesis on CPU-optimized fast neural artistic style transfer for web deployment."
    ],
    skills: ["Computer science", "Artificial intelligence", "Machine learning", "Software engineering"],
    metric: "8.74 GPA",
    visual: { kind: "logo", key: "amity" },
  },
  {
    id: "incoming-hiwin-fellow",
    section: "experience",
    status: "Incoming",
    dates: "Sep 2027 — Sep 2029",
    sortDate: "2027-09",
    title: "Corporate Sponsorship Fellow",
    organization: "HIWIN Technologies · INTENSE Program",
    location: "Taichung, Taiwan",
    summary: "Incoming R&D placement associated with Taiwan’s industry–academia advanced-manufacturing fellowship program.",
    preview: [
      "This is a future, scheduled placement beginning in September 2027; it is not current employment.",
      "The role is expected to connect graduate training in advanced manufacturing with industrial research and development at HIWIN Technologies."
    ],
    skills: ["Smart manufacturing", "Industrial R&D", "Precision engineering", "Technical communication"],
    visual: { kind: "logo", key: "hiwin" },
  },
  {
    id: "tag-twin",
    section: "experience",
    status: "Current",
    dates: "Aug 2025 — present",
    sortDate: "2025-08",
    title: "Graduate Research Student",
    organization: "Smart City Artificial Intelligence Research Lab · CCU",
    location: "Chiayi, Taiwan",
    summary: "Developing the UE5 presentation and integration layer for the Disaster Response Digital Twin Model research demonstrator in Minxiong.",
    preview: [
      "Integrated five flood states, four evacuation routes, 100 moving agents, 24,408 trajectory samples, two shelters, and ranked response events in one synchronized UE5 presentation layer.",
      "Profiled the geospatial playback pipeline, reducing reported wet-frame switching from multi-second JSON updates to approximately 16–22 ms cached transitions."
    ],
    skills: ["Unreal Engine 5", "C++", "QGIS", "Geospatial systems", "Scientific visualization"],
    destination: "/research/tag-twin",
    visual: { kind: "logo", key: "ccu" },
  },
  {
    id: "ai-sustainability-internship",
    section: "experience",
    status: "Completed",
    dates: "Jul — Oct 2023",
    sortDate: "2023-07",
    title: "Summer Research Intern / Team Lead",
    organization: "India–Taiwan Joint Research Center for AI · CCU",
    location: "Chiayi, Taiwan",
    summary: "Led a six-person international team applying computer vision to working-time analysis in Taiwan’s fisheries context.",
    preview: [
      "Coordinated interns from India, Taiwan, and Denmark while contributing to a video-processing and custom-tuned YOLOv8 detection pipeline.",
      "The team produced an end-to-end research prototype and a comprehensive technical report; public performance claims remain withheld pending an approved source record."
    ],
    skills: ["Computer vision", "YOLOv8", "Research leadership", "Video processing"],
    destination: "/experience/ai-sustainability-internship",
    visual: { kind: "logo", key: "ccu" },
  },
  {
    id: "intense-fellowship",
    section: "award",
    status: "Current",
    dates: "Sep 2025 — present",
    sortDate: "2025-09",
    title: "INTENSE Program Fellow",
    organization: "Taiwan Government–Industry–Academia Fellowship · HIWIN",
    location: "Taiwan",
    summary: "Selected for an international industrial-talent program supporting graduate study and industry-connected advanced-manufacturing development.",
    preview: [
      "The fellowship supports full graduate tuition and a sponsored living allowance through the National Development Fund and partner company HIWIN Technologies.",
      "It is recognition and program sponsorship; the associated HIWIN R&D placement is separately labeled as incoming."
    ],
    skills: ["Advanced manufacturing", "Industry–academia collaboration", "International mobility"],
    visual: { kind: "logo", key: "hiwin" },
  },
  {
    id: "amity-merit-scholarship",
    section: "award",
    status: "Completed",
    dates: "Aug 2021 — Aug 2025",
    sortDate: "2021-08",
    title: "Dr. Ashok K. Chauhan 100% Merit Scholarship",
    organization: "Amity University Mumbai",
    location: "Mumbai, India",
    summary: "Received a full-tuition merit scholarship supporting undergraduate computer-science study.",
    preview: ["The scholarship recognized academic performance and supported the tuition cost of the bachelor’s program during its documented award period."],
    skills: ["Academic merit", "Computer science"],
    visual: { kind: "logo", key: "amity" },
  },
  {
    id: "nirmaan-hackathon",
    section: "award",
    status: "Completed",
    dates: "Feb 2022",
    sortDate: "2022-02",
    title: "2nd Place · NIRMAN Hackathon",
    organization: "Amity University Mumbai",
    location: "Mumbai, India",
    summary: "Placed second in a 48-hour hackathon with an API for converting 2D ArcGIS shapefiles into rendered 3D models.",
    preview: ["Designed a Python and Flask workflow that accepted ArcGIS shapefiles, generated 3D geometry, and rendered the result through a web application."],
    skills: ["Python", "Flask", "ArcGIS", "Rapid prototyping"],
    destination: "/projects",
    visual: { kind: "logo", key: "amity" },
  },
  {
    id: "image-color-restoration",
    section: "project",
    status: "Completed",
    dates: "2024",
    sortDate: "2024-03",
    title: "Image Color Restoration",
    organization: "Independent machine-learning project",
    location: "Mumbai, India",
    summary: "A TensorFlow image-colorization system using an autoencoder and pix2pix-inspired adversarial workflow for grayscale images.",
    preview: ["Explored learned color restoration, training behavior, image preprocessing, and a web-facing workflow for uploading and colorizing monochrome images."],
    skills: ["TensorFlow", "Autoencoders", "GANs", "Image processing"],
    destination: "/projects",
    visual: { kind: "icon", key: "image-restoration" },
  },
  {
    id: "neural-style-transfer",
    section: "project",
    status: "Completed",
    dates: "May 2024 — Jun 2025",
    sortDate: "2024-05",
    title: "CPU-Optimized Neural Artistic Style Transfer",
    organization: "Undergraduate thesis",
    location: "Amity University Mumbai",
    summary: "A fast neural artistic style-transfer model optimized for web inference on servers without dedicated GPUs.",
    preview: ["The thesis investigated CPU-only training and deployment constraints, then optimized a fast style-transfer workflow for a real-time web application."],
    skills: ["PyTorch", "Neural networks", "CPU optimization", "Web inference"],
    destination: "/projects",
    visual: { kind: "icon", key: "style-transfer" },
  },
  {
    id: "arcgis-to-3d",
    section: "project",
    status: "Completed",
    dates: "Feb 2022",
    sortDate: "2022-02",
    title: "2D Satellite Data to 3D City Models",
    organization: "NIRMAN Hackathon project",
    location: "Mumbai, India",
    summary: "A Flask web API converting ArcGIS shapefiles into rendered 3D geometry using native PyOpenGL tooling.",
    preview: ["The 48-hour prototype prioritized a compact server-side pipeline capable of ingesting 2D geospatial data and returning a rendered 3D result through a web interface."],
    skills: ["Python", "Flask", "ArcGIS", "PyOpenGL"],
    destination: "/projects",
    visual: { kind: "icon", key: "geospatial-3d" },
  },
] satisfies ResumeEntry[];

export const resumeEntries = validateUnique(records.map((record) => resumeEntrySchema.parse(record)), "resume entry");

export const resumeSkills = [
  "Data visualization",
  "Machine learning",
  "Deep learning",
  "Statistical analysis",
  "Computer vision",
  "Collaborative problem solving",
  "Leadership",
  "Technical & business presentation",
] as const;

export function entriesForSection(section: ResumeEntry["section"]) {
  return resumeEntries.filter((entry) => entry.section === section);
}
