import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { SectionHeading } from "@/components/section-heading";

export const metadata: Metadata = { title: "AI & Sustainability Research Internship", description: "A 2023 computer-vision research internship in Taiwan’s fisheries context.", alternates: { canonical: "/experience/ai-sustainability-internship" } };

export default function InternshipPage() {
  return <main id="main"><div className="page-shell"><Breadcrumbs section="Experience" current="AI & Sustainability internship" /><header className="page-hero"><div><p className="eyebrow mono">Research internship / Jun—Aug 2023</p><h1>Computer vision<br />for <em>work analysis.</em></h1></div><div className="page-hero-meta"><p className="lede">A six-person international internship team explored CCTV-based working-time analysis for Taiwan’s fisheries sector.</p><p className="mono">Role / Research Team Lead<br />Location / Chiayi, Taiwan<br />Method / YOLOv8 + video preprocessing</p></div></header><section className="section"><SectionHeading number="01" eyebrow="Context & role" title="Leading an applied research team." /><div className="prose-grid"><aside className="mono">International team<br />India<br />Taiwan<br />Denmark</aside><div className="prose"><p className="lead">I coordinated six interns working across computer vision, preprocessing, experimental review, and technical communication.</p><p>The project investigated whether CCTV video could support more systematic records of working activity in a fisheries setting. The team combined a tuned YOLOv8 detector with video preprocessing and logging logic.</p><div className="limitation-note"><strong>Scope note</strong>This page describes the internship project at a high level. Model performance, deployment status, participant data, and institutional adoption are not claimed without a verified public report.</div></div></div></section><section className="section"><SectionHeading number="02" eyebrow="Contribution" title="Research coordination plus implementation." /><div className="boundary"><div className="owned"><h3>Responsibilities</h3><ul><li>Coordinating work across a multicultural intern team</li><li>Structuring tasks, reviews, and research communication</li><li>Contributing to computer-vision and video-processing experiments</li><li>Connecting technical output to the domain problem</li></ul></div><div className="upstream"><h3>Evidence still needed</h3><ul><li>Approved project imagery and demonstration media</li><li>Verified benchmark protocol and model metrics</li><li>Confirmed final deployment or adoption wording</li><li>Public collaborator attribution and dataset permissions</li></ul></div></div></section></div></main>;
}
